export const payments = [
  {
    paidBy: 'venkat',
    priceData: {
      venkat: '1353',
      nitheesh: '1353',
      gnana: '1353',
      gnanendra: '1353',
      nitin: '1353',
      gowtham: '1353',
      rana: '1353',
      amala: '1353',
      athira: '1353',
      anubhuti: '1353',
      prachi: '1353',
      anto: '1353',
      mani: '1353',
      kesavan: '1353',
    },
    title: 'Wonderla Ticket',
    description: 'Entry Ticket in Wonderla',
    total: '18940',
  },
  {
    paidBy: 'venkat',
    priceData: {
      venkat: '40',
      nitheesh: '40',
      gnana: '40',
      gnanendra: '40',
      nitin: '40',
    },
    total: '200',
    title: 'Auto',
    description: 'Auto From Bidadi to Wonderla',
  },
  {
    priceData: {
      venkat: '84',
      nitheesh: '84',
      gnana: '84',
      gnanendra: '84',
      nitin: '84',
      kesavan: '100',
    },
    paidBy: 'venkat',
    title: 'Bus',
    description: 'Bus from Wonderla to Kengeri',
    total: '520',
  },
  {
    priceData: {
      venkat: '75',
      nitheesh: '75',
      gnana: '75',
      gnanendra: '75',
      nitin: '75',
    },
    paidBy: 'nitheesh',
    title: 'Train Ticket',
    description: 'Train Ticket from Mysore to Bidadi',
    total: '375',
  },
  {
    priceData: {
      venkat: '60',
      nitheesh: '60',
      gnana: '60',
      gnanendra: '60',
      nitin: '60',
    },
    paidBy: 'nitheesh',
    title: 'Train Ticket',
    description: 'Train Ticket from Kengeri to Mysore',
    total: '300',
  },
  {
    priceData: {
      venkat: '87.5',
      amala: '87.5',
      athira: '87.5',
      anto: '87.5',
    },
    title: 'Recoil Video',
    description: 'Coaster video took for 4 people',
    total: '350',
    paidBy: 'nitheesh',
  },
  {
    priceData: {
      venkat: '155',
      anto: '155',
      nitheesh: '390',
      gowtham: '390',
      amala: '195',
      kesavan: '155',
      mani: '155',
      athira: '195',
    },
    paidBy: 'nitheesh',
    title: 'Lunch',
    description: 'Lunch in Wonderla Chillies',
    total: '1790',
  },
  {
    priceData: {
      amala: '68',
      rana: '68',
      athira: '68',
      anubhuti: '68',
      prachi: '68',
      gowtham: '70',
    },
    title: 'BreakFast Car Group',
    description: 'Breakfast for guys in car',
    total: '410',
    paidBy: 'gowtham',
  },
  {
    priceData: {
      gowtham: '250',
      rana: '250',
      amala: '250',
      athira: '250',
      anubhuti: '250',
      prachi: '250',
    },
    title: 'Dinner Car Gang',
    description: 'Dinner in nandhanavana palace - car gang',
    total: '1500',
    paidBy: 'gowtham',
  },
  {
    priceData: {
      venkat: '40',
      nitheesh: '40',
      gnana: '40',
      gnanendra: '40',
      nitin: '50',
    },
    title: 'Breakfast - Gypsies',
    description: 'Breakfast in Train Gypsie gang',
    total: '210',
    paidBy: 'nitin',
  },
  {
    priceData: {
      venkat: '40',
      amala: '40',
      athira: '40',
      anto: '40',
      mani: '40',
    },
    paidBy: 'anto',
    title: 'Waterride Pic',
    description: 'Waterride Picture by Anto',
    total: '200',
  },
  {
    priceData: {
      venkat: '22',
      nitheesh: '22',
      gnana: '22',
      gnanendra: '22',
      nitin: '22',
    },
    title: 'Snacks Kengeri',
    description: 'Water & Snacks in Kengeri Station',
    total: '110',
    paidBy: 'nitin',
  },
  {
    priceData: {
      nitin: '135',
      rana: '135',
      anubhuti: '135',
      prachi: '135',
    },
    title: 'Lunch Nitin',
    description: 'Lunch with nitin & co',
    total: '540',
    paidBy: 'nitin',
  },
  {
    priceData: {
      venkat: '40',
      nitin: '40',
      athira: '40',
      amala: '40',
    },
    title: 'Refreshment near Recoil',
    description: 'Snacks and juice near recoil',
    total: '160',
    paidBy: 'nitin',
  },
  {
    priceData: {
      anubhuti: '333.33',
      gowtham: '333.33',
      rana: '333.33',
      prachi: '333.33',
      athira: '333.33',
      amala: '333.33',
    },
    title: 'Fuel Charges',
    description: 'Car Fuel Charges',
    total: '2000',
    paidBy: 'rana',
  },
];
